#!/bin/sh
# A scripted stand-in for the provider CLI behind the `research_investigate`
# agent step. Orbit starts it exactly as it would start the real CLI (argv and
# the prompt on stdin, the run worktree as the working directory, the run's
# ORBIT_* environment) and reads one terminal `agent_message` carrying the
# response envelope from its stdout.
#
# It does what the activity's instruction tells a real agent to do and nothing
# else: inspect the reserved record, write code, an input and an artifact in the
# run worktree, write the README and manifest with the worktree-mode writer,
# name the new files as task context and persist an execution summary. It never
# commits, merges or moves the task.
#
# `@CONTROL_DIR@/<task id>` holds one line, "<variant> <research id>", chosen by
# the test per task; `@RESEARCH_BIN@` is the binary under test.
set -eu

cat > /dev/null

workspace=$(pwd -P)
task=${ORBIT_TASK_ID:?the run supplies ORBIT_TASK_ID}
run=${ORBIT_RUN_ID:?the run supplies ORBIT_RUN_ID}
research=@RESEARCH_BIN@
read -r variant rid < "@CONTROL_DIR@/$task"

if [ "$(git rev-parse --show-toplevel)" != "$workspace" ]; then
    echo "worktree_mismatch: $workspace" >&2
    exit 1
fi

dir=$(cd research && ls -d "$rid"-*)
record=research/$dir
mkdir -p "$record/code" "$record/artifacts" "$record/data" .orbit/tmp

blob=$("$research" --json research show --corpus "$workspace" --id "$rid" \
    | sed -n 's/.*"git_blob":"\([0-9a-f]*\)".*/\1/p')
[ -n "$blob" ] || { echo "no git_blob for $rid" >&2; exit 1; }

sha256() {
    if command -v sha256sum > /dev/null 2>&1; then sha256sum "$1" | cut -d' ' -f1; else shasum -a 256 "$1" | cut -d' ' -f1; fi
}

# The experiment: a small deterministic computation with a control. A faulty
# control (the `failed_controls` variant) is modelled by an offset in the
# control's input, not by editing the result.
cat > "$record/code/experiment.sh" <<'CODE'
#!/bin/sh
# usage: experiment.sh SAMPLE.csv [CONTROL_OFFSET]
# The control recomputes the mean from the same sample; it must agree.
set -eu
mean() { awk -F, 'NR > 1 { s += $2 + off; n += 1 } END { printf "%.1f", s / n }' off="$1" "$2"; }
sample=$(mean 0 "$1")
control=$(mean "${2:-0}" "$1")
status=passed
[ "$sample" = "$control" ] || status=failed
printf '{"mean": %s, "control_mean": %s, "control": "%s"}\n' "$sample" "$control" "$status"
CODE
printf 'id,value\n1,10\n2,20\n3,30\n' > "$record/data/sample.csv"
size=$(wc -c < "$record/data/sample.csv" | tr -d ' ')
digest=$(sha256 "$record/data/sample.csv")

offset=0
if [ "$variant" = failed_controls ]; then offset=11.5; fi
sh "$record/code/experiment.sh" "$record/data/sample.csv" "$offset" > "$record/artifacts/result.json"
cat "$record/artifacts/result.json" >&2

case "$variant" in
failed_controls)
    result="The sample mean was 20.0 but the control gave 31.5, so the control failed. The result is inconclusive; it neither supports nor refutes the hypothesis."
    limitations="The control disagreed with the sample, so no claim is made."
    ;;
*)
    result="The sample mean was 20.0 and the control gave the same value, so the control passed. The computation supports the stated expectation on this sample."
    limitations="Three rows only; this is a smoke-scale sample."
    ;;
esac

{
    printf '## Question\n\nDoes the sample mean match its shuffled control?\n\n'
    printf '## Method\n\nComputed the mean of data/sample.csv with code/experiment.sh and compared it with a shuffled control.\n\n'
    printf '## Result\n\n%s\n\n' "$result"
    printf '## Limitations\n\n%s\n\n' "$limitations"
    if [ "$variant" != missing_section ]; then
        printf '## Next\n\nRepeat on a larger sample.\n'
    fi
} > .orbit/tmp/body.md

printf '{"inputs":[{"name":"sample.csv","source":"generated by the scripted agent","sha256":"%s","size":%s,"fetch":"printf in code/experiment.sh"}]}\n' \
    "$digest" "$size" > .orbit/tmp/manifest.json

recorded_run=$run
if [ "$variant" = wrong_run ]; then recorded_run=jrun-some-other-run; fi

"$research" --json research revise --corpus "$workspace" --mode worktree --id "$rid" \
    --expected-blob "$blob" --status done --orbit-task "$task" --orbit-run "$recorded_run" \
    --body-file .orbit/tmp/body.md --manifest-file .orbit/tmp/manifest.json >&2

# Tamper with the input after the manifest pinned its digest.
if [ "$variant" = tampered_digest ]; then
    printf '4,40\n' >> "$record/data/sample.csv"
fi

# Allocate an ID by hand, which only primary-mode `create` may do.
if [ "$variant" = allocated_id ]; then
    printf -- '---\nid: Q900\ntitle: Sneaked in\nstatus: open\ntags: []\nderived_from: []\ncreated: 2026-01-01\nupdated: 2026-01-01\nanswered_by: []\n---\nAllocated by hand in the run worktree.\n' > questions/Q900-sneaked-in.md
fi

orbit tool run orbit.task.update --input "{\"id\":\"$task\",\"context_files\":[\"dir:$record\",\"file:$record/code/experiment.sh\",\"file:$record/artifacts/result.json\"],\"allow_missing_context\":true,\"execution_summary\":\"Scripted investigation of $rid ($variant): wrote the README, manifest, experiment code and result artifact with the worktree-mode writer. Checks: orbit-research research check not run; the job's validate step is the gate.\"}" > /dev/null

printf '%s\n' "{\"type\":\"item.completed\",\"item\":{\"id\":\"item_1\",\"type\":\"agent_message\",\"text\":\"{\\\"schemaVersion\\\":1,\\\"status\\\":\\\"success\\\",\\\"result\\\":{\\\"summary\\\":\\\"scripted $variant investigation\\\",\\\"research_id\\\":\\\"$rid\\\"},\\\"error\\\":null}\"}}"
