use super::worktree::{Run, blob, result, run};
use super::writer::git;
use crate::{
    corpus::Corpus,
    delivery::{Expected, Reason},
};
use serde_json::json;
use sha2::{Digest, Sha256};
use std::fs;

const EXPECTED: Expected<'static> = Expected {
    research_id: None,
    task: "task-1",
    run: "run-1",
};
const README: &str = "research/R001-first-study/README.md";
const DATA: &str = "research/R001-first-study/data";

/// A run worktree whose reserved R001 was written by the worktree-mode writer
/// with one local input whose digest and size the manifest pins.
fn delivered() -> Run {
    let run = run();
    let corpus = Corpus::open(&run.linked).unwrap();
    let bytes = b"a,b\n1,2\n";
    let mut edit = result();
    edit.manifest = Some(json!({"inputs": [{
        "name": "input.csv",
        "source": "fixture",
        "sha256": format!("{:x}", Sha256::digest(bytes)),
        "size": bytes.len(),
        "fetch": "generated by the fixture",
    }]}));
    corpus
        .revise("R001", &blob(&corpus, "R001"), &edit)
        .unwrap();
    fs::write(run.linked.join(DATA).join("input.csv"), bytes).unwrap();
    run
}

fn reasons(run: &Run, expected: &Expected<'_>) -> Vec<Reason> {
    let report = Corpus::open(&run.linked)
        .unwrap()
        .validate_delivery(expected)
        .unwrap();
    report
        .findings
        .iter()
        .map(|finding| finding.reason)
        .collect()
}

fn edit_readme(run: &Run, from: &str, to: &str) {
    let path = run.linked.join(README);
    let text = fs::read_to_string(&path).unwrap();
    assert!(text.contains(from), "fixture README lacks {from:?}");
    fs::write(path, text.replacen(from, to, 1)).unwrap();
}

#[test]
fn a_written_reserved_record_passes_without_touching_the_checkout() {
    let run = delivered();
    let status = git(&run.linked, &["status", "--porcelain"]);
    let report = Corpus::open(&run.linked)
        .unwrap()
        .validate_delivery(&EXPECTED)
        .unwrap();
    assert!(report.valid(), "{:?}", report.findings);
    assert_eq!(report.research_id.as_deref(), Some("R001"));
    assert_eq!(report.path.as_deref(), Some(README));
    assert_eq!(report.revision, git(&run.linked, &["rev-parse", "HEAD"]));
    assert!(report.unverified_inputs.is_empty());
    assert_eq!(git(&run.linked, &["status", "--porcelain"]), status);
}

#[test]
fn absent_input_bytes_are_reported_unverified_not_failed() {
    let run = delivered();
    fs::remove_file(run.linked.join(DATA).join("input.csv")).unwrap();
    let report = Corpus::open(&run.linked)
        .unwrap()
        .validate_delivery(&EXPECTED)
        .unwrap();
    assert!(report.valid(), "{:?}", report.findings);
    assert_eq!(report.unverified_inputs, ["input.csv"]);
}

#[test]
fn a_missing_section_fails() {
    let run = delivered();
    edit_readme(&run, "## Limitations\n\nOne run.\n\n", "");
    assert_eq!(reasons(&run, &EXPECTED), [Reason::SectionMissing]);
}

#[test]
fn a_placeholder_section_fails() {
    let run = delivered();
    edit_readme(&run, "Controls failed.", "Pending.");
    assert_eq!(reasons(&run, &EXPECTED), [Reason::SectionPlaceholder]);
    edit_readme(&run, "Pending.", "");
    assert_eq!(reasons(&run, &EXPECTED), [Reason::SectionPlaceholder]);
}

#[test]
fn the_unwritten_stub_fails_on_every_placeholder() {
    let run = run();
    let report = Corpus::open(&run.linked)
        .unwrap()
        .validate_delivery(&Expected {
            research_id: Some("R001"),
            ..EXPECTED
        })
        .unwrap();
    let reasons: Vec<Reason> = report.findings.iter().map(|f| f.reason).collect();
    assert_eq!(
        reasons,
        [
            Reason::SectionPlaceholder,
            Reason::OrbitTaskMismatch,
            Reason::OrbitRunMismatch,
        ]
    );
    assert!(
        report.findings[0]
            .message
            .contains("`## Method`, `## Result`, `## Limitations`, `## Next`"),
        "{}",
        report.findings[0].message
    );
}

#[test]
fn provenance_must_name_this_task_and_run() {
    let run = delivered();
    assert_eq!(
        reasons(
            &run,
            &Expected {
                run: "run-2",
                ..EXPECTED
            }
        ),
        [Reason::OrbitRunMismatch]
    );
    assert_eq!(
        reasons(
            &run,
            &Expected {
                task: "task-2",
                ..EXPECTED
            }
        ),
        [Reason::OrbitTaskMismatch]
    );
}

#[test]
fn a_tampered_input_digest_or_size_fails() {
    let run = delivered();
    fs::write(run.linked.join(DATA).join("input.csv"), b"a,b\n1,3\n").unwrap();
    assert_eq!(reasons(&run, &EXPECTED), [Reason::ArtifactDigestMismatch]);

    let manifest = run.linked.join(DATA).join("manifest.json");
    fs::write(&manifest, "{\"inputs\": 1}").unwrap();
    assert_eq!(reasons(&run, &EXPECTED), [Reason::ManifestInvalid]);
    fs::remove_file(&manifest).unwrap();
    assert_eq!(reasons(&run, &EXPECTED), [Reason::ManifestInvalid]);
}

#[test]
fn a_dangling_lineage_target_fails() {
    let run = delivered();
    edit_readme(&run, "derived_from: []", "derived_from:\n- Q009");
    let reasons = reasons(&run, &EXPECTED);
    assert_eq!(reasons[0], Reason::DanglingLineage, "{reasons:?}");
}

#[test]
fn an_id_allocated_in_the_worktree_fails() {
    let run = delivered();
    let stray = run.linked.join("research/R003-stray");
    fs::create_dir_all(&stray).unwrap();
    fs::write(
        stray.join("README.md"),
        "---\nid: R003\ntitle: Stray\nstatus: planned\ntags: []\nderived_from: []\ncreated: 2026-01-01\nupdated: 2026-01-01\ntests: []\n---\n\nStray.\n",
    )
    .unwrap();
    assert_eq!(reasons(&run, &EXPECTED), [Reason::IdAllocated]);
}

#[test]
fn a_changed_or_removed_other_record_fails() {
    let run = delivered();
    let question = run.linked.join("questions/Q001-a-question.md");
    let text = fs::read_to_string(&question).unwrap();
    fs::write(&question, text.replace("Why?", "Why not?")).unwrap();
    assert_eq!(reasons(&run, &EXPECTED), [Reason::OtherRecordChanged]);
    fs::remove_file(&question).unwrap();
    assert_eq!(reasons(&run, &EXPECTED), [Reason::OtherRecordChanged]);
}

#[test]
fn a_record_is_needed_and_must_match_the_binding() {
    let run = run();
    assert_eq!(reasons(&run, &EXPECTED), [Reason::ResearchUnbound]);
    let run = delivered();
    let other = Expected {
        research_id: Some("R002"),
        ..EXPECTED
    };
    assert_eq!(reasons(&run, &other), [Reason::ResearchUnbound]);
    let absent = Expected {
        research_id: Some("R009"),
        ..EXPECTED
    };
    let primary = Corpus::open(run.primary.path()).unwrap();
    let report = primary.validate_delivery(&absent).unwrap();
    assert_eq!(report.findings[0].reason, Reason::ResearchUnbound);
}

#[test]
fn an_unparseable_record_fails_as_invalid() {
    let run = delivered();
    edit_readme(&run, "status: done", "status: finished");
    assert_eq!(reasons(&run, &EXPECTED), [Reason::RecordInvalid]);
}
